---
name: md-lint

on:
  workflow_call:
    inputs:
      report-type:
        description: rumdl report type (annotations, github, summary).
        type: string
        default: annotations

permissions: {}

jobs:
  rumdl:
    name: rumdl
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Run rumdl
        uses: rvben/rumdl@f8bdeb6a73c5f0741b58c25da2d38af5ee21b6e0 # v0.1.87
        with:
          report-type: ${{ inputs.report-type }}
